const skills = ["React", "Next.js", "TypeScript", "Node.js", "APIs REST", "Supabase", "PostgreSQL", "MongoDB", "Docker", "n8n"];
const experience = ["Interfaces reativas e responsivas com React.js, Material UI e Redux.", "Criação e consumo de APIs REST, com comunicação em tempo real via Socket.io.", "Modelagem de dados com MongoDB e colaboração em fluxos de CI/CD e code review."];

export default function Home() {
  return <main>
    <section className="hero" id="inicio"><nav className="nav container" aria-label="Navegação principal"><a className="brand" href="#inicio" aria-label="Página inicial">AC<span>.</span></a><div className="nav-links"><a href="#sobre">Sobre</a><a href="#projetos">Projetos</a><a href="#contato">Contato</a></div><a className="nav-cta" href="mailto:devbetortiz@gmail.com">Vamos conversar <span>↗</span></a></nav><div className="hero-content container"><p className="eyebrow"><i /> Disponível para oportunidades remotas</p><h1>Construo produtos web<br /><em>que fazem sentido.</em></h1><div className="hero-bottom"><p className="intro">Sou Alberto Cabral, desenvolvedor full stack júnior. Transformo ideias em experiências digitais funcionais, rápidas e bem cuidadas.</p><a className="circle-link" href="#projetos" aria-label="Ver projetos selecionados">↓</a></div></div><div className="hero-number" aria-hidden="true">01</div></section>
    <section className="about section container" id="sobre"><div className="section-label"><span>01</span> SOBRE MIM</div><div className="about-grid"><h2>Código com propósito,<br />atenção aos <em>detalhes.</em></h2><div className="about-copy"><p>Desenvolvedor com foco em aplicações web full stack, integrações e automação de processos. Gosto de unir boas práticas de engenharia a interfaces que tornam a tecnologia mais simples para as pessoas.</p><p>Tenho perfil analítico, organizado e colaborativo — sempre aprendendo e buscando entregar soluções consistentes.</p><a className="text-link" href="mailto:devbetortiz@gmail.com">Conheça meu trabalho <span>→</span></a></div></div><div className="skill-cloud" aria-label="Tecnologias e ferramentas">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></section>
    <section className="projects section" id="projetos"><div className="container"><div className="section-label light"><span>02</span> PROJETOS SELECIONADOS</div><div className="project-list"><article className="project-featured"><a href="https://www.visualbarbearia.com.br" target="_blank" rel="noreferrer" className="project-visual"><div className="browser"><span /><span /><span /></div><div className="visual-content"><small>VISUAL BARBEARIA</small><strong>Seu próximo corte<br />começa aqui.</strong><b>Agendar horário →</b></div><div className="visual-orbit">VB</div></a><div className="project-info"><p className="project-index">01 / 02</p><h3>Visual<br />Barbearia</h3><p>Plataforma SaaS para curso de barbearia com autenticação, streaming e módulo financeiro.</p><div className="tags"><span>Next.js</span><span>Supabase</span><span>Stripe</span><span>Bunny.net</span></div></div></article><article className="project-secondary"><div className="law-art"><span>LP</span><p>LAW<br />PARTNER</p><i>Legal solutions<br />for a new era</i></div><div className="secondary-info"><p className="project-index">02 / 02</p><h3>Law Partner</h3><p>Landing page institucional com formulário de contato integrado para uma consultoria jurídica.</p><div className="tags"><span>Next.js</span><span>Formulário</span><span>Responsivo</span></div><a className="text-link light-link" href="https://www.lawpartner.com.br" target="_blank" rel="noreferrer">Ver projeto <span>↗</span></a></div></article></div></div></section>
    <section className="experience section container"><div className="section-label"><span>03</span> EXPERIÊNCIA</div><div className="experience-grid"><div><p className="role">Developer JavaScript<br />Full Stack Júnior</p><h2>PSG /<br /><em>Inovvati</em></h2><p className="period">SET 2022 — MAI 2023</p></div><ul>{experience.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <footer id="contato"><div className="container footer-inner"><p className="eyebrow"><i /> VAMOS CONSTRUIR ALGO JUNTOS</p><h2>Tem um desafio<br />em mente?</h2><a className="email" href="mailto:devbetortiz@gmail.com">devbetortiz@gmail.com <span>↗</span></a><div className="footer-bottom"><span>© 2026 Alberto Cabral</span><div><a href="https://github.com/devbetortiz" target="_blank" rel="noreferrer">GitHub</a><a href="https://www.linkedin.com/in/alberto-cabral-ortiz-de-medeiros-26662011b" target="_blank" rel="noreferrer">LinkedIn</a></div><span>Campo Grande, MS · Brasil</span></div></div></footer>
  </main>;
}
