const services = [["01", "Aplicações Next.js", "SSR, App Router, dashboards, SaaS e experiências responsivas.", "NEXT.JS / TS"], ["02", "APIs & Integrações", "Node.js, bancos de dados, autenticação e integrações de serviços.", "REST / SQL"], ["03", "Automação & IA", "n8n, agentes inteligentes e fluxos que eliminam trabalho repetitivo.", "N8N / AI"]];
const projects = [["analytics", "ANALYTICS", "84.2K", "↑ 18.4%", "Dashboard SaaS", "Painel de métricas e gestão para operação digital.", "Next.js • Supabase • Recharts"], ["workflow", "WORKFLOW", "TRIGGER → AI → CRM", "✓ RUNNING", "Plataforma de Automação", "Fluxos inteligentes conectando atendimento, IA e CRM.", "Next.js • n8n • OpenAI"], ["erp", "ERP WEB", "PEDIDOS  128", "ESTOQUE  94%", "Sistema de Gestão", "Gestão web responsiva para processos e indicadores.", "Next.js • Prisma • PostgreSQL"]];
const steps = [["01", "Descoberta", "Objetivos, usuários e requisitos essenciais."], ["02", "Arquitetura", "Dados, integrações e decisões técnicas."], ["03", "Construção", "UI, código, testes e ciclos curtos."], ["04", "Deploy & evolução", "Entrega, métricas e melhoria contínua."]];
const tech = ["Next.js", "TypeScript", "React", "Node.js", "PostgreSQL", "Prisma", "Supabase", "Tailwind CSS", "n8n", "Docker", "Vercel", "Git"];

export default function Home() {
  return <main>
    <section className="hero" id="inicio"><nav className="nav" aria-label="Navegação principal"><a className="brand" href="#inicio">DEVBETORTIZ</a><div className="nav-links"><a href="#inicio">Início</a><a href="#projetos">Projetos</a><a href="#stack">Stack</a><a href="#sobre">Sobre</a><a href="#contato">Contato</a></div><span className="availability">● DISPONÍVEL</span></nav><div className="hero-content"><p className="eyebrow">NEXT.JS • TYPESCRIPT • WEB SYSTEMS</p><h1>Transformo ideias em<br />sistemas web de alto impacto.</h1><p className="intro">Desenvolvimento de aplicações modernas, escaláveis e rápidas com Next.js — do produto ao deploy.</p><div className="hero-actions"><a className="button primary" href="#projetos">Ver projetos <span>→</span></a><a className="button secondary" href="#contato">Falar comigo</a></div></div><div className="code-window"><div className="window-controls"><i /><i /><i /></div><pre>{`const developer = {
  stack: ["Next.js", "TypeScript", "Node.js"], focus: "performance + UX",
  status: "building what comes next"
}`}</pre></div></section>
    <section className="expertise" id="sobre"><div className="section-inner"><p className="section-eyebrow">O QUE EU CONSTRUO</p><h2>Sistemas pensados para crescer.</h2><p className="section-subtitle">Arquitetura sólida, interfaces claras e performance desde a primeira linha de código.</p><div className="service-grid">{services.map(([number, title, description, tag]) => <article className="service-card" key={number}><strong>{number}</strong><h3>{title}</h3><p>{description}</p><span>{tag}</span></article>)}</div></div></section>
    <section className="projects" id="projetos"><div className="section-inner"><p className="section-eyebrow">TRABALHOS SELECIONADOS</p><h2>Projetos que resolvem problemas reais.</h2><p className="section-subtitle">Uma seleção de produtos digitais com foco em engenharia, experiência e resultado.</p><div className="project-grid">{projects.map(([type, heading, metric, status, title, description, stack]) => <article className="project-card" key={title}><div className={`project-visual ${type}`}>{heading}<br /><b>{metric}</b><br /><em>{status}</em></div><h3>{title}</h3><p>{description}</p><span>{stack}</span><a href="#contato">Ver case ↗</a></article>)}</div></div></section>
    <section className="stack" id="stack"><div className="section-inner"><p className="section-eyebrow">TECNOLOGIAS</p><h2>Stack moderna. Decisões pragmáticas.</h2><p className="section-subtitle">Ferramentas escolhidas pelo problema — não pela moda da semana.</p><div className="tech-grid">{tech.map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section className="process"><div className="section-inner"><p className="section-eyebrow">PROCESSO</p><h2>Do problema ao deploy, sem fumaça.</h2><p className="section-subtitle">Um fluxo enxuto para reduzir risco e transformar requisitos em software utilizável.</p><div className="process-grid">{steps.map(([number, title, description]) => <article className="step-card" key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="contact" id="contato"><p>TEM UM PROJETO EM MENTE?</p><h2>Vamos construir algo<br />que mereça existir.</h2><span>Se você precisa de um sistema web rápido, confiável e preparado para evoluir, vamos conversar.</span><a href="mailto:devbetortiz@gmail.com">Iniciar conversa →</a></section>
    <footer><div><strong>DEVBETORTIZ</strong><span>Next.js Web Systems Developer</span></div><div><p><a href="https://github.com/devbetortiz" target="_blank" rel="noreferrer">GitHub</a><a href="https://www.linkedin.com/in/alberto-cabral-ortiz-de-medeiros-26662011b" target="_blank" rel="noreferrer">LinkedIn</a><a href="mailto:devbetortiz@gmail.com">Email</a></p><span>© 2026 — Construído com Next.js</span></div></footer>
  </main>;
}
